
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/damian/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.1.0-26-amd64 - x86_64
...
